# Generated by Django 3.2.12 on 2022-03-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('age_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'life',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('purpose_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('welfare_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('welfare_ori_id', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_area', models.CharField(max_length=2)),
                ('welfare_child', models.IntegerField(blank=True, null=True)),
                ('welfare_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_crit', models.TextField(blank=True, null=True)),
                ('welfare_dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_group', models.BigIntegerField(blank=True, null=True)),
                ('welfare_gu', models.CharField(max_length=2)),
                ('welfare_howto', models.TextField(blank=True, null=True)),
                ('welfare_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_service_content', models.TextField(blank=True, null=True)),
                ('welfare_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_site_link', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_target_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'welfare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarefamily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfarefamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarelife',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfarelife',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarepurpose',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfarepurpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfaretarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfaretarget',
                'managed': False,
            },
        ),
    ]
