# Generated by Django 3.2.12 on 2022-03-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soboksobok_app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welfare_similarwelfare',
            fields=[
                ('welfare_welfare_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'similarwelfare',
                'managed': False,
            },
        ),
    ]
