# Generated by Django 4.0.3 on 2022-04-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soboksobok_app2', '0002_welfare_similarwelfare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_created_at', models.DateTimeField(blank=True, null=True)),
                ('comment_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyWelfarefamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'family_welfarefamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HibernateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hibernate_sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword_cnt', models.BigIntegerField(blank=True, null=True)),
                ('keyword_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LifeWelfarelife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'life_welfarelife',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likewelfare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'likewelfare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('qna_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('qna_content', models.TextField()),
                ('qna_created_at', models.DateTimeField(blank=True, null=True)),
                ('qna_title', models.CharField(blank=True, max_length=100, null=True)),
                ('qna_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selectfamily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'selectfamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selecttarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'selecttarget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetWelfaretarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'target_welfaretarget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'used',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('birth', models.CharField(blank=True, max_length=255, null=True)),
                ('child', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('female', models.BigIntegerField(blank=True, null=True)),
                ('male', models.BigIntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=20, null=True)),
                ('role_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user_group', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('refresh_token_seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'user_refresh_token',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.DeleteModel(
            name='Welfare_similarwelfare',
        ),
        migrations.DeleteModel(
            name='Welfarepurpose',
        ),
    ]
