# Generated by Django 4.0.3 on 2022-04-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soboksobok_app2', '0003_comment_familywelfarefamily_hibernatesequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welfare_similarwelfare',
            fields=[
                ('welfare_welfare_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'similarwelfare',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FamilyWelfarefamily',
        ),
        migrations.DeleteModel(
            name='HibernateSequence',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='LifeWelfarelife',
        ),
        migrations.DeleteModel(
            name='Likewelfare',
        ),
        migrations.DeleteModel(
            name='Qna',
        ),
        migrations.DeleteModel(
            name='Selectfamily',
        ),
        migrations.DeleteModel(
            name='Selecttarget',
        ),
        migrations.DeleteModel(
            name='TargetWelfaretarget',
        ),
        migrations.DeleteModel(
            name='Used',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRefreshToken',
        ),
    ]
