# Generated by Django 3.1.5 on 2022-03-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_created_at', models.DateTimeField(blank=True, null=True)),
                ('comment_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyWelfarefamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'family_welfarefamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HibernateSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hibernate_sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword_cnt', models.BigIntegerField(blank=True, null=True)),
                ('keyword_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('age_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'life',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LifeWelfarelife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'life_welfarelife',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likewelfare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'likewelfare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('purpose_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('purpose_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurposeWelfarepurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purpose_welfarepurpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('qna_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('qna_content', models.TextField()),
                ('qna_created_at', models.DateTimeField(blank=True, null=True)),
                ('qna_title', models.CharField(blank=True, max_length=100, null=True)),
                ('qna_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selectfamily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'selectfamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selecttarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'selecttarget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetWelfaretarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'target_welfaretarget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'used',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('birth', models.CharField(blank=True, max_length=255, null=True)),
                ('child', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('email', models.CharField(max_length=512, unique=True)),
                ('email_verified_yn', models.CharField(max_length=1)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_at', models.DateTimeField()),
                ('password', models.CharField(max_length=128)),
                ('profile_image_url', models.CharField(max_length=512)),
                ('provider_type', models.CharField(max_length=20)),
                ('role_type', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('refresh_token_seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'user_refresh_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('welfare_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('welfare_area', models.CharField(max_length=2)),
                ('welfare_child', models.IntegerField(blank=True, null=True)),
                ('welfare_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_crit', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_gu', models.CharField(max_length=2)),
                ('welfare_howto', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_service_content', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_site_link', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('welfare_target_detail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'welfare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarefamily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfarefamily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarelife',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfarelife',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfarepurpose',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfarepurpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Welfaretarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'welfaretarget',
                'managed': False,
            },
        ),
    ]
