# Generated by Django 4.0.3 on 2022-04-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soboksobok_app', '0004_similarwelfare_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.DeleteModel(
            name='PurposeWelfarepurpose',
        ),
        migrations.DeleteModel(
            name='Similarwelfare',
        ),
        migrations.DeleteModel(
            name='Welfarepurpose',
        ),
    ]
